### ISSUE TITLE
Posted errors after running simple test of Pifacerelayplus

### ISSUE THREAD

**Issue by retiredtech** [piface/pifacerelayplus#3]
Just installed a new pifacerelayplus relay unit onto a B+ V1.2 RPI. Followed documentation on setup then initial testing which all worked perfectly. Next copied simple Python3 program from doc to further test relay operations, which again worked perfectly.
CODE: SELECT ALL
import pifacerelayplus
import time
pfr = pifacerelayplus.PiFaceRelayPlus(pifacerelayplus.RELAY)
pfr.relays[0].toggle()
time.sleep(2)
pfr.relays[0].toggle()

After the program python3 relayonoff.py was run the following was displayed:

pi@raspberrypi:sudo python3 relayonoff.py
Exception ignored in: <bound method PiFaceRelayPlus.__del__ of <pifacerelayplus.
core.PiFaceRelayPlus object at 0X76a687f0>>
Traceback (most recent call last):
File "/usr/lib/python3/dist—packages/pifacerelayplus/core.py", line 227, in
del
File "/usr/lib/python3/dist—packages/pifacerelayplus/core.py", line 238, in di
sable_interrupts
File "/usr/lib/python3/dist—packages/pifacecommon/interrupts.py", line 242, in
gpio_interrupts_disable
File "/usr/lib/python3/dist—packages/pifacecommon/interrupts.py", line 412, in
set_gpio_interrupt_edge
NameError: name 'open' is not defined

Considering that the program runs successfully it appears the module "python3-pifacerelayplus" must have errors still embedded in it.  At this point I cannot use the hardware until the software issue is resolved or that there is an alternative coding routine available.

**Comment by csoutreach** [comment]
It could be the operating system or included libraries have been changed by e.g. Raspberry Pi. Can you just confirm which OS you're using and then I'll install it and look to see if the way interrupts are handled has changed.

**Comment by retiredtech** [comment]
I actually ran these tests on both the RASPBIAN JESSIE WITH PIXEL and RASPBIAN JESSIE LITE downloaded directly from raspberrypi.org web site. Both failed the same way as described above.  In both cases I also did a: apt-get update and upgrade.  I also tried with the EXTRA relay unit installed and also without.  If I do a cat /proc/version now I get:  LINUX Version 4.4.38-V7+ gcc version 4.9.3.

**Comment by retiredtech** [comment]
I must have mistakenly closed this hitting the wrong key.  This is to remain OPEN!!!

**Comment by retiredtech** [comment]
Where does this issue stand?  I may return the pifacerelay units and go with external relays using  GPIO connections if this cannot be resolved.  Advise.

**Comment by csoutreach** [comment]
Closing the issue confused us, so we assumed the problem was resolved. If it helps you plan, it's now scheduled to be examined on Weds.

**Comment by retiredtech** [comment]
Thank you.  Yes, I just hit the "close and comment" button instead of the "comment" in error.  Guess it must be a sign of getting old! (I'm only 81).

**Comment by csoutreach** [comment]
It's very easy to do! Anyway, to keep you updated on progress, so you can decide what you want to do, it's going to take a little longer to fix the issue -- hopefully around a week. Some changes have been made in the OS and I can't find any documentation of them, so we're going to have to pick it apart to work out what needs updating on our part.

**Comment by retiredtech** [comment]
Thanks for your effort.  I will put this aside until you complete the task.  I have other things to do anyway.

**Comment by manasystemizer** [comment]
I had the same issue. It turned out the speed on the spi transfer was too high. It seems fixed on masterin pifacecommon, but is not included in the python-pifacerelayplus package for Raspberry Pi.
This was fixed ages ago (pull request #23 in pifacecommon). Would it be possible to have new release of the Rasbbpian package?
